package main


import(
	"bufio"
	"fmt"
	"os"
)

func CountingValues() {
	what_i_write := bufio.NewScanner(os.Stdin)
	words := make(map[string]int)

	what_i_write.Split(bufio.ScanWords) // returns space separated text
	
	for what_i_write.Scan() {
		words[what_i_write.Text()]++ // Text returns the most recent token generated by a call to Scanner.Scan as a newly allocated string holding its bytes
	}

	fmt.Println(len(words), "unique words")

}

// go run ./cmd/5-arrays < cmd/texts.txt